/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface GalleryPost {
  'id' : bigint,
  'imageData' : string,
  'likes' : bigint,
  'caption' : string,
  'comments' : Array<string>,
}
export interface MedicalNote { 'date' : Time, 'text' : string }
export interface PetProfile {
  'age' : bigint,
  'name' : string,
  'energyLevel' : bigint,
  'petType' : string,
}
export interface Reminder {
  'id' : bigint,
  'time' : Time,
  'enabled' : boolean,
  'reminderType' : string,
  'lastDone' : Time,
}
export type Time = bigint;
export interface VaccinationRecord {
  'date' : Time,
  'vaccineName' : string,
  'notes' : string,
}
export interface WeightLog { 'weight' : number, 'date' : Time }
export interface _SERVICE {
  'addGalleryPost' : ActorMethod<[GalleryPost], undefined>,
  'addMedicalNote' : ActorMethod<[MedicalNote], undefined>,
  'addReminder' : ActorMethod<[Reminder], undefined>,
  'addVaccinationRecord' : ActorMethod<[VaccinationRecord], undefined>,
  'addWeightLog' : ActorMethod<[WeightLog], undefined>,
  'deleteGalleryPost' : ActorMethod<[bigint], undefined>,
  'deleteMedicalNote' : ActorMethod<[Time], undefined>,
  'deleteReminder' : ActorMethod<[bigint], undefined>,
  'deleteVaccinationRecord' : ActorMethod<[Time], undefined>,
  'deleteWeightLog' : ActorMethod<[Time], undefined>,
  'getAllGalleryPosts' : ActorMethod<[], Array<GalleryPost>>,
  'getAllMedicalNotes' : ActorMethod<[], Array<MedicalNote>>,
  'getAllReminders' : ActorMethod<[], Array<Reminder>>,
  'getAllVaccinationRecords' : ActorMethod<[], Array<VaccinationRecord>>,
  'getAllWeightLogs' : ActorMethod<[], Array<WeightLog>>,
  'getGalleryPost' : ActorMethod<[bigint], GalleryPost>,
  'getMedicalNote' : ActorMethod<[Time], MedicalNote>,
  'getPetProfile' : ActorMethod<[], [] | [PetProfile]>,
  'getReminder' : ActorMethod<[bigint], Reminder>,
  'getVaccinationRecord' : ActorMethod<[Time], VaccinationRecord>,
  'getWeightLog' : ActorMethod<[Time], WeightLog>,
  'setPetProfile' : ActorMethod<[PetProfile], undefined>,
  'updateGalleryPost' : ActorMethod<[GalleryPost], undefined>,
  'updateMedicalNote' : ActorMethod<[MedicalNote], undefined>,
  'updateReminder' : ActorMethod<[Reminder], undefined>,
  'updateVaccinationRecord' : ActorMethod<[VaccinationRecord], undefined>,
  'updateWeightLog' : ActorMethod<[WeightLog], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];