/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const GalleryPost = IDL.Record({
  'id' : IDL.Nat,
  'imageData' : IDL.Text,
  'likes' : IDL.Nat,
  'caption' : IDL.Text,
  'comments' : IDL.Vec(IDL.Text),
});
export const Time = IDL.Int;
export const MedicalNote = IDL.Record({ 'date' : Time, 'text' : IDL.Text });
export const Reminder = IDL.Record({
  'id' : IDL.Nat,
  'time' : Time,
  'enabled' : IDL.Bool,
  'reminderType' : IDL.Text,
  'lastDone' : Time,
});
export const VaccinationRecord = IDL.Record({
  'date' : Time,
  'vaccineName' : IDL.Text,
  'notes' : IDL.Text,
});
export const WeightLog = IDL.Record({ 'weight' : IDL.Float64, 'date' : Time });
export const PetProfile = IDL.Record({
  'age' : IDL.Nat,
  'name' : IDL.Text,
  'energyLevel' : IDL.Nat,
  'petType' : IDL.Text,
});

export const idlService = IDL.Service({
  'addGalleryPost' : IDL.Func([GalleryPost], [], []),
  'addMedicalNote' : IDL.Func([MedicalNote], [], []),
  'addReminder' : IDL.Func([Reminder], [], []),
  'addVaccinationRecord' : IDL.Func([VaccinationRecord], [], []),
  'addWeightLog' : IDL.Func([WeightLog], [], []),
  'deleteGalleryPost' : IDL.Func([IDL.Nat], [], []),
  'deleteMedicalNote' : IDL.Func([Time], [], []),
  'deleteReminder' : IDL.Func([IDL.Nat], [], []),
  'deleteVaccinationRecord' : IDL.Func([Time], [], []),
  'deleteWeightLog' : IDL.Func([Time], [], []),
  'getAllGalleryPosts' : IDL.Func([], [IDL.Vec(GalleryPost)], ['query']),
  'getAllMedicalNotes' : IDL.Func([], [IDL.Vec(MedicalNote)], ['query']),
  'getAllReminders' : IDL.Func([], [IDL.Vec(Reminder)], ['query']),
  'getAllVaccinationRecords' : IDL.Func(
      [],
      [IDL.Vec(VaccinationRecord)],
      ['query'],
    ),
  'getAllWeightLogs' : IDL.Func([], [IDL.Vec(WeightLog)], ['query']),
  'getGalleryPost' : IDL.Func([IDL.Nat], [GalleryPost], ['query']),
  'getMedicalNote' : IDL.Func([Time], [MedicalNote], ['query']),
  'getPetProfile' : IDL.Func([], [IDL.Opt(PetProfile)], ['query']),
  'getReminder' : IDL.Func([IDL.Nat], [Reminder], ['query']),
  'getVaccinationRecord' : IDL.Func([Time], [VaccinationRecord], ['query']),
  'getWeightLog' : IDL.Func([Time], [WeightLog], ['query']),
  'setPetProfile' : IDL.Func([PetProfile], [], []),
  'updateGalleryPost' : IDL.Func([GalleryPost], [], []),
  'updateMedicalNote' : IDL.Func([MedicalNote], [], []),
  'updateReminder' : IDL.Func([Reminder], [], []),
  'updateVaccinationRecord' : IDL.Func([VaccinationRecord], [], []),
  'updateWeightLog' : IDL.Func([WeightLog], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const GalleryPost = IDL.Record({
    'id' : IDL.Nat,
    'imageData' : IDL.Text,
    'likes' : IDL.Nat,
    'caption' : IDL.Text,
    'comments' : IDL.Vec(IDL.Text),
  });
  const Time = IDL.Int;
  const MedicalNote = IDL.Record({ 'date' : Time, 'text' : IDL.Text });
  const Reminder = IDL.Record({
    'id' : IDL.Nat,
    'time' : Time,
    'enabled' : IDL.Bool,
    'reminderType' : IDL.Text,
    'lastDone' : Time,
  });
  const VaccinationRecord = IDL.Record({
    'date' : Time,
    'vaccineName' : IDL.Text,
    'notes' : IDL.Text,
  });
  const WeightLog = IDL.Record({ 'weight' : IDL.Float64, 'date' : Time });
  const PetProfile = IDL.Record({
    'age' : IDL.Nat,
    'name' : IDL.Text,
    'energyLevel' : IDL.Nat,
    'petType' : IDL.Text,
  });
  
  return IDL.Service({
    'addGalleryPost' : IDL.Func([GalleryPost], [], []),
    'addMedicalNote' : IDL.Func([MedicalNote], [], []),
    'addReminder' : IDL.Func([Reminder], [], []),
    'addVaccinationRecord' : IDL.Func([VaccinationRecord], [], []),
    'addWeightLog' : IDL.Func([WeightLog], [], []),
    'deleteGalleryPost' : IDL.Func([IDL.Nat], [], []),
    'deleteMedicalNote' : IDL.Func([Time], [], []),
    'deleteReminder' : IDL.Func([IDL.Nat], [], []),
    'deleteVaccinationRecord' : IDL.Func([Time], [], []),
    'deleteWeightLog' : IDL.Func([Time], [], []),
    'getAllGalleryPosts' : IDL.Func([], [IDL.Vec(GalleryPost)], ['query']),
    'getAllMedicalNotes' : IDL.Func([], [IDL.Vec(MedicalNote)], ['query']),
    'getAllReminders' : IDL.Func([], [IDL.Vec(Reminder)], ['query']),
    'getAllVaccinationRecords' : IDL.Func(
        [],
        [IDL.Vec(VaccinationRecord)],
        ['query'],
      ),
    'getAllWeightLogs' : IDL.Func([], [IDL.Vec(WeightLog)], ['query']),
    'getGalleryPost' : IDL.Func([IDL.Nat], [GalleryPost], ['query']),
    'getMedicalNote' : IDL.Func([Time], [MedicalNote], ['query']),
    'getPetProfile' : IDL.Func([], [IDL.Opt(PetProfile)], ['query']),
    'getReminder' : IDL.Func([IDL.Nat], [Reminder], ['query']),
    'getVaccinationRecord' : IDL.Func([Time], [VaccinationRecord], ['query']),
    'getWeightLog' : IDL.Func([Time], [WeightLog], ['query']),
    'setPetProfile' : IDL.Func([PetProfile], [], []),
    'updateGalleryPost' : IDL.Func([GalleryPost], [], []),
    'updateMedicalNote' : IDL.Func([MedicalNote], [], []),
    'updateReminder' : IDL.Func([Reminder], [], []),
    'updateVaccinationRecord' : IDL.Func([VaccinationRecord], [], []),
    'updateWeightLog' : IDL.Func([WeightLog], [], []),
  });
};

export const init = ({ IDL }) => { return []; };