/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type Time = bigint;
export interface Reminder {
    id: bigint;
    time: Time;
    enabled: boolean;
    reminderType: string;
    lastDone: Time;
}
export interface PetProfile {
    age: bigint;
    name: string;
    energyLevel: bigint;
    petType: string;
}
export interface VaccinationRecord {
    date: Time;
    vaccineName: string;
    notes: string;
}
export interface WeightLog {
    weight: number;
    date: Time;
}
export interface GalleryPost {
    id: bigint;
    imageData: string;
    likes: bigint;
    caption: string;
    comments: Array<string>;
}
export interface MedicalNote {
    date: Time;
    text: string;
}
export interface backendInterface {
    addGalleryPost(post: GalleryPost): Promise<void>;
    addMedicalNote(note: MedicalNote): Promise<void>;
    addReminder(reminder: Reminder): Promise<void>;
    addVaccinationRecord(record: VaccinationRecord): Promise<void>;
    addWeightLog(log: WeightLog): Promise<void>;
    deleteGalleryPost(id: bigint): Promise<void>;
    deleteMedicalNote(date: Time): Promise<void>;
    deleteReminder(id: bigint): Promise<void>;
    deleteVaccinationRecord(date: Time): Promise<void>;
    deleteWeightLog(date: Time): Promise<void>;
    getAllGalleryPosts(): Promise<Array<GalleryPost>>;
    getAllMedicalNotes(): Promise<Array<MedicalNote>>;
    getAllReminders(): Promise<Array<Reminder>>;
    getAllVaccinationRecords(): Promise<Array<VaccinationRecord>>;
    getAllWeightLogs(): Promise<Array<WeightLog>>;
    getGalleryPost(id: bigint): Promise<GalleryPost>;
    getMedicalNote(date: Time): Promise<MedicalNote>;
    getPetProfile(): Promise<PetProfile | null>;
    getReminder(id: bigint): Promise<Reminder>;
    getVaccinationRecord(date: Time): Promise<VaccinationRecord>;
    getWeightLog(date: Time): Promise<WeightLog>;
    setPetProfile(profile: PetProfile): Promise<void>;
    updateGalleryPost(post: GalleryPost): Promise<void>;
    updateMedicalNote(note: MedicalNote): Promise<void>;
    updateReminder(reminder: Reminder): Promise<void>;
    updateVaccinationRecord(record: VaccinationRecord): Promise<void>;
    updateWeightLog(log: WeightLog): Promise<void>;
}
import type { PetProfile as _PetProfile } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addGalleryPost(arg0: GalleryPost): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addGalleryPost(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addGalleryPost(arg0);
            return result;
        }
    }
    async addMedicalNote(arg0: MedicalNote): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addMedicalNote(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addMedicalNote(arg0);
            return result;
        }
    }
    async addReminder(arg0: Reminder): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addReminder(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addReminder(arg0);
            return result;
        }
    }
    async addVaccinationRecord(arg0: VaccinationRecord): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addVaccinationRecord(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addVaccinationRecord(arg0);
            return result;
        }
    }
    async addWeightLog(arg0: WeightLog): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addWeightLog(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addWeightLog(arg0);
            return result;
        }
    }
    async deleteGalleryPost(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteGalleryPost(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteGalleryPost(arg0);
            return result;
        }
    }
    async deleteMedicalNote(arg0: Time): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteMedicalNote(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteMedicalNote(arg0);
            return result;
        }
    }
    async deleteReminder(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteReminder(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteReminder(arg0);
            return result;
        }
    }
    async deleteVaccinationRecord(arg0: Time): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteVaccinationRecord(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteVaccinationRecord(arg0);
            return result;
        }
    }
    async deleteWeightLog(arg0: Time): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteWeightLog(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteWeightLog(arg0);
            return result;
        }
    }
    async getAllGalleryPosts(): Promise<Array<GalleryPost>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllGalleryPosts();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllGalleryPosts();
            return result;
        }
    }
    async getAllMedicalNotes(): Promise<Array<MedicalNote>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllMedicalNotes();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllMedicalNotes();
            return result;
        }
    }
    async getAllReminders(): Promise<Array<Reminder>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllReminders();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllReminders();
            return result;
        }
    }
    async getAllVaccinationRecords(): Promise<Array<VaccinationRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllVaccinationRecords();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllVaccinationRecords();
            return result;
        }
    }
    async getAllWeightLogs(): Promise<Array<WeightLog>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllWeightLogs();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllWeightLogs();
            return result;
        }
    }
    async getGalleryPost(arg0: bigint): Promise<GalleryPost> {
        if (this.processError) {
            try {
                const result = await this.actor.getGalleryPost(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getGalleryPost(arg0);
            return result;
        }
    }
    async getMedicalNote(arg0: Time): Promise<MedicalNote> {
        if (this.processError) {
            try {
                const result = await this.actor.getMedicalNote(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMedicalNote(arg0);
            return result;
        }
    }
    async getPetProfile(): Promise<PetProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getPetProfile();
                return from_candid_opt_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPetProfile();
            return from_candid_opt_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async getReminder(arg0: bigint): Promise<Reminder> {
        if (this.processError) {
            try {
                const result = await this.actor.getReminder(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getReminder(arg0);
            return result;
        }
    }
    async getVaccinationRecord(arg0: Time): Promise<VaccinationRecord> {
        if (this.processError) {
            try {
                const result = await this.actor.getVaccinationRecord(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getVaccinationRecord(arg0);
            return result;
        }
    }
    async getWeightLog(arg0: Time): Promise<WeightLog> {
        if (this.processError) {
            try {
                const result = await this.actor.getWeightLog(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getWeightLog(arg0);
            return result;
        }
    }
    async setPetProfile(arg0: PetProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setPetProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setPetProfile(arg0);
            return result;
        }
    }
    async updateGalleryPost(arg0: GalleryPost): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateGalleryPost(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateGalleryPost(arg0);
            return result;
        }
    }
    async updateMedicalNote(arg0: MedicalNote): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateMedicalNote(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateMedicalNote(arg0);
            return result;
        }
    }
    async updateReminder(arg0: Reminder): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateReminder(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateReminder(arg0);
            return result;
        }
    }
    async updateVaccinationRecord(arg0: VaccinationRecord): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateVaccinationRecord(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateVaccinationRecord(arg0);
            return result;
        }
    }
    async updateWeightLog(arg0: WeightLog): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateWeightLog(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateWeightLog(arg0);
            return result;
        }
    }
}
function from_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_PetProfile]): PetProfile | null {
    return value.length === 0 ? null : value[0];
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
